name: Integration Tests

on:
  repository_dispatch:
    types: [integration-test]
  workflow_dispatch:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight UTC

jobs:
  check:
    name: "Integration test for check: ${{ matrix.check }}"
    runs-on: namespace-profile-pareto-linux
    strategy:
      fail-fast: false
      matrix:
        check: [firewall, screenlock, luks]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/devenv
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build .#checks.x86_64-linux.${{ matrix.check }}