# Run all tests, linters, code analysis and other QA tasks on
# every push to master and PRs.
#
# To SSH into the runner to debug a failure, add the following step before
# the failing step
#       - uses: mxschmitt/action-tmate@v3
#         with:
#           install-dependencies: false

name: Unit Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - main

# Prevent multiple jobs running after fast subsequent pushes
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  dependabot:
    needs: [ test ]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}}
    steps:
    - id: metadata
      uses: dependabot/fetch-metadata@d7267f607e9d3fb96fc2fbe83e0af444713e90b7 # v2.3.0
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
    - run: |
        gh pr review --approve "$PR_URL"
        gh pr merge --squash --auto "$PR_URL"
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  test:
    name: Tests
    runs-on: namespace-profile-pareto-linux
    steps:
    - uses: namespacelabs/nscloud-checkout-action@63f88aa089f855c0d888a2b1baffcbc44cc7262e # v6
    - uses: ./.github/actions/devenv
      with:
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
    - run: devenv test -d
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage
        path: coverage.txt # Make sure to use the same file name you chose for the "-coverprofile" in the "Test" step
    - uses: actions/setup-go@v5
      with:
        go-version: 1.24
      if: github.ref == 'refs/heads/main'
    - uses: ncruces/go-coverage-report@main
      if: github.ref == 'refs/heads/main'
      with:
        report: true
        chart: true
        amend: true
        coverage-file: coverage.txt
      continue-on-error: true
  code_coverage:
    name: "Code coverage report"
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      actions: read
      pull-requests: write
    steps:
    - uses: teamniteo/go-coverage-report@v3
      with:
        coverage-artifact-name: "code-coverage"
        coverage-file-name: "coverage.txt"
